BookingParking/BookingParking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booking.urls', namespace='booking')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BookingParking/booking/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'booking'

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('confirm_email/<int:user_id>/<str:token>/', views.confirm_email, name='confirm_email'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('parking/<int:parking_id>/', views.parking_detail, name='parking_detail'),
    path('parking/<int:parking_id>/', views.parking_detail, name='parking_detail'),
    path('payment/<int:booking_id>/', views.payment_view, name='payment'),
    path('pay_penalty/<int:booking_id>/', views.pay_penalty, name='pay_penalty'),
    path('booking_success/<int:booking_id>/', views.booking_success, name='booking_success'),
    path('profile/', views.profile_view, name='profile'),
    path('open_barrier/<int:booking_id>/', views.open_barrier, name='open_barrier'),
    path('leave_parking/<int:booking_id>/', views.leave_parking, name='leave_parking'),
    path('extend_parking/<int:booking_id>/', views.extend_parking, name='extend_parking'),
    path('check-status/', views.check_booking_status, name='check_booking_status'),
    path('confirm-exit/<int:booking_id>/', views.confirm_exit, name='confirm_exit'),
    path('fines/', views.user_fines, name='user_fines'),
    path('update-car-number/', views.update_car_number, name='update_car_number'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='booking/password_reset_form.html',
             email_template_name='booking/password_reset_email.html',
             subject_template_name='booking/password_reset_subject.txt',
             success_url='/password-reset/done/'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='booking/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='booking/password_reset_confirm.html',
             success_url='/reset/done/'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='booking/password_reset_complete.html'),
         name='password_reset_complete'),
    path('metrics/', views.metrics_view, name='metrics'),
    path('profile/add-parking/', views.add_parking_zone, name='add_parking_zone'),
    path('profile/verify-account/', views.verify_account, name='verify_account'),
    path('profile/my-parking/', views.my_parking_zones, name='my_parking_zones'),
    path('profile/my-parking/<int:pk>/hide/', views.hide_parking_zone, name='hide_parking_zone'),
    path('profile/my-parking/<int:pk>/edit/', views.edit_parking_zone, name='edit_parking_zone'),
    path('profile/my-parking/<int:pk>/show/', views.show_parking_zone, name='show_parking_zone'),
    path('check-availability/<int:parking_id>/', views.check_availability, name='check_availability'),
    path('servo/', views.servo_control, name='servo_control'),
]

BookingParking/booking/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.conf import settings

from django.db.models import Sum
from django.utils.timezone import now

class UserManager(BaseUserManager):
    def create_user(self, email, password=None, car_number=None, **extra_fields):
        if not email:
            raise ValueError("Пользователь должен иметь email")
        email = self.normalize_email(email)
        user = self.model(email=email, car_number=car_number, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, car_number=None, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)
        return self.create_user(email, password, car_number, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    car_number = models.CharField(max_length=20, blank=True, null=True, verbose_name="Номер автомобиля")
    is_active = models.BooleanField(default=False, verbose_name="Активен (подтверждение email)")
    is_staff = models.BooleanField(default=False, verbose_name="Администратор")
    is_blocked = models.BooleanField(default=False, verbose_name="Заблокирован")
    date_joined = models.DateTimeField(default=now, verbose_name="Дата регистрации")
    passport_data = models.CharField(max_length=255, blank=True, null=True, verbose_name="Паспортные данные")
    is_verified = models.BooleanField(default=False, verbose_name="Подтверждённый пользователь")
    ACCOUNT_TYPE_CHOICES = (
        ('individual', 'Частное лицо'),
        ('company', 'Компания'),
    )
    phone_number = models.CharField(max_length=255, blank=True, null=True, verbose_name="Номер телефона")
    account_type = models.CharField(max_length=255, choices=ACCOUNT_TYPE_CHOICES, blank=True, null=True, verbose_name="Тип аккаунта")
    company_name = models.CharField(max_length=255, blank=True, null=True, verbose_name="Название компании")
    inn = models.CharField(max_length=255, blank=True, null=True, verbose_name="ИНН компании")

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

class ParkingZone(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название парковочной зоны")
    address = models.TextField(verbose_name="Адрес")
    latitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    barrier_ip = models.GenericIPAddressField(null=True, blank=True, verbose_name="IP шлагбаума")
    total_places = models.PositiveIntegerField(verbose_name="Количество мест")
    tariff_per_hour = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Тариф за час")
    is_available = models.BooleanField(default=True, verbose_name="Доступна")
    photo = models.ImageField(upload_to='parking_photos/', null=True, blank=True, verbose_name="Фото парковки")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Владелец парковки")
    is_visible = models.BooleanField(default=True, verbose_name="Отображать парковку на сайте")
    barrier_mac = models.CharField(max_length=32, null=True, blank=True)

    def __str__(self):
        return self.name
class Booking(models.Model):
    STATUS_CHOICES = (
        ('pending', 'Ожидает оплаты'),
        ('active', 'Активна'),
        ('inside', 'На парковке'),
        ('finished', 'Завершена'),
        ('overdue', 'Просрочена'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    parkingzone = models.ForeignKey(ParkingZone, on_delete=models.CASCADE)
    start_datetime = models.DateTimeField()
    end_datetime = models.DateTimeField()
    reservation_code = models.CharField(max_length=50, unique=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    paid = models.BooleanField(default=False)
    penalty = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0, verbose_name="Цена бронирования")
    def __str__(self):
        return f"Бронь {self.reservation_code} для {self.user.email}"
    def total_fine_amount(self):
        return self.fines.aggregate(Sum('amount'))['amount__sum'] or 0
    def total_cost(self):
        return float(self.price) + float(self.total_fine_amount())
    def has_unpaid_fines(self):
        return self.fines.filter(is_paid=False).exists()
class Fine(models.Model):
    booking = models.ForeignKey('Booking', on_delete=models.CASCADE, related_name='fines')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    issued_at = models.DateTimeField(auto_now_add=True)
    reason = models.TextField(default='Просрочка парковки')
    is_paid = models.BooleanField(default=False)

    def __str__(self):
        return f"Штраф {self.amount} руб. за {self.booking}"


class Review(models.Model):
    parking = models.ForeignKey(ParkingZone, on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField()
    comment = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('parking', 'user')

    def __str__(self):
        return f"{self.rating}★ для {self.parking.name}"

class DeviceCommand(models.Model):
    device_id = models.CharField(max_length=32, db_index=True)
    status = models.IntegerField(choices=[(0, "Открыть"), (1, "Открыть вручную"), (2, "Закрыть")])
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.device_id} => {self.status}"

BookingParking/booking/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from .models import User, ParkingZone, Review

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, label="Пароль")
    confirm_password = forms.CharField(widget=forms.PasswordInput, label="Подтверждение пароля")

    class Meta:
        model = User
        fields = ['email']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")
        if password and confirm_password and password != confirm_password:
            self.add_error('confirm_password', "Пароли не совпадают")
        return cleaned_data

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("На эту почту уже зарегистрирован аккаунт.")
        return email

class LoginForm(AuthenticationForm):
    username = forms.EmailField(widget=forms.EmailInput(attrs={'autofocus': True}), label="Email")

class ParkingZoneForm(forms.ModelForm):
    class Meta:
        model = ParkingZone
        fields = ['name', 'address', 'total_places', 'tariff_per_hour', 'is_available', 'photo']
class ParkingZoneEditForm(forms.ModelForm):
    class Meta:
        model = ParkingZone
        fields = ['name', 'address', 'latitude', 'longitude', 'total_places', 'tariff_per_hour', 'barrier_ip', 'photo']


class VerificationForm(forms.Form):
    account_type = forms.ChoiceField(
        choices=[('individual', 'Частное лицо'), ('company', 'Компания')],
        label="Тип аккаунта",
        widget=forms.Select(attrs={'id': 'id_account_type'})
    )
    phone_number = forms.CharField(
        required=True,
        label="Номер телефона",
        widget=forms.TextInput(attrs={'placeholder': 'Номер телефона'})
    )
    passport_data = forms.CharField(
        required=False,
        label="Паспортные данные",
        widget=forms.TextInput(attrs={'placeholder': 'Серия и номер паспорта'})
    )
    company_name = forms.CharField(
        required=False,
        label="Название компании"
    )
    inn = forms.CharField(
        required=False,
        label="ИНН компании"
    )

    def clean(self):
        cleaned_data = super().clean()
        account_type = cleaned_data.get('account_type')

        if account_type == 'individual':
            if not cleaned_data.get('passport_data'):
                self.add_error('passport_data', "Необходимо указать паспортные данные.")
        elif account_type == 'company':
            if not cleaned_data.get('company_name'):
                self.add_error('company_name', "Необходимо указать название компании.")
            if not cleaned_data.get('inn'):
                self.add_error('inn', "Необходимо указать ИНН.")
        return cleaned_data

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']
        labels = {
            'rating': 'Оценка (от 1 до 5)',
            'comment': 'Комментарий',
        }
        widgets = {
            'rating': forms.NumberInput(attrs={'min': 1, 'max': 5, 'class': 'form-control'}),
            'comment': forms.Textarea(attrs={'rows': 3, 'class': 'form-control'}),
        }

BookingParking/templates/booking/booking_success.html
{% extends "booking/base.html" %}
{% block title %}Бронирование успешно{% endblock %}
{% block content %}
<div class="success-card">
  <h2>Бронирование успешно оформлено!</h2>
  <p><strong>Адрес парковки:</strong> {{ booking.parkingzone.address }}</p>
  <p><strong>Время парковки:</strong> c {{ booking.start_datetime }} до {{ booking.end_datetime }}</p>
  <p><strong>Код бронирования:</strong> {{ booking.reservation_code }}</p>

  <h3>Открыть шлагбаум</h3>

  {% if booking.status == 'active' and now >= booking.start_datetime %}
      <a href="{% url 'booking:open_barrier' booking.id %}" class="btn btn-success">Открыть шлагбаум</a>
  {% elif booking.status == 'inside' %}
      <a href="{% url 'booking:confirm_exit' booking.id %}" class="btn btn-danger">Выехать с парковки</a>
  {% elif booking.status == 'overdue' %}
      {% if booking.penalty > 0 %}
          <a href="{% url 'booking:pay_penalty' booking.id %}" class="btn btn-warning">
              Оплатить штраф ({{ booking.penalty|floatformat:0 }} руб.)
          </a>
      {% else %}
          <a href="{% url 'booking:leave_parking' booking.id %}" class="btn btn-danger">Выехать с парковки</a>
      {% endif %}
  {% else %}
      <p class="text-muted">Бронирование ещё не началось</p>
  {% endif %}

  <p class="mt-3">
    <a href="{% url 'booking:home' %}" class="btn btn-outline-primary">Вернуться на главную</a>
  </p>
</div>
{% endblock %}

BookingParking/templates/booking/password_change_done.html
{% extends "booking/base.html" %}
{% block title %}Пароль изменён
{% endblock %}

{% block content %}
<div class="auth-card position-relative">
<a href="{% url 'booking:home' %}" class="back-arrow-glass" title="На главную"><span>←</span></a>

  <div class="alert alert-success">
    <h4>Готово!</h4>
    <p>Пароль успешно изменён.</p>
    <a href="{% url 'booking:profile' %}" class="btn btn-primary">Вернуться в профиль</a>
  </div>
</div>
{% endblock %}

BookingParking/templates/booking/profile.html
{% extends "booking/base.html" %}
{% load tz %}
{% block title %}Мой профиль{% endblock %}

{% block content %}
<h2 class="mb-3">Профиль пользователя</h2>

<a href="{% url 'booking:home' %}" class="btn btn-outline-primary mb-4">← Вернуться на главную</a>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<div class="btn-group d-flex mb-4" role="group">
  <button class="btn btn-info w-100" onclick="showSection('current')">Бронирования</button>
  <button class="btn btn-info w-100" onclick="showSection('history')">История</button>
  <button class="btn btn-info w-100" onclick="showSection('fines')">Штрафы</button>
  <button class="btn btn-info w-100" onclick="showSection('verified')">Верификация</button> 
    <button class="btn btn-info w-100" onclick="showSection('settings')">Настройки</button>

</div>

<section id="section-current" style="display: block;">
  <h4>Текущие бронирования</h4>
  {% if active_bookings %}
    <div class="container">
      {% for booking in active_bookings %}
        <div class="card mb-3">
          <div class="card-body" data-booking-id="{{ booking.id }}">
            <h5 class="card-title">{{ booking.parkingzone.name }}</h5>
            <p class="card-text">
                <div id="map-{{ booking.id }}" style="width: 100%; height: 250px;" class="mt-3 rounded"></div>
              <strong>Период:</strong>
              {{ booking.start_datetime|localtime|date:"d.m.Y H:i" }} – 
              {{ booking.end_datetime|localtime|date:"d.m.Y H:i" }}<br>
              <strong>Статус:</strong> {{ booking.get_status_display }}
            </p>
            <div class="action-container">
              {% if booking.status == 'active' and now >= booking.start_datetime %}
    <a href="{% url 'booking:open_barrier' booking.id %}" class="btn btn-success">Открыть шлагбаум</a>
{% elif booking.status == 'inside' %}
    <a href="{% url 'booking:confirm_exit' booking.id %}" class="btn btn-danger">Выехать с парковки</a>
{% elif booking.status == 'overdue' %}
    {% if booking.has_unpaid_fines %}
        <a href="{% url 'booking:pay_penalty' booking.id %}" class="btn btn-warning">
            Оплатить штраф ({{ booking.total_fine_amount|floatformat:2 }} руб.)
        </a>
    {% endif %}
    <a href="{% url 'booking:leave_parking' booking.id %}" class="btn btn-danger">Выехать с парковки</a>
{% else %}
    <span class="text-muted">Бронирование ещё не началось</span>
{% endif %}
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  {% else %}
    <p>Нет активных бронирований.</p>
  {% endif %}
</section>

<section id="section-history" style="display: none;">
  <h4>История бронирований</h4>
  {% if finished_bookings %}
      <div class="row mb-3">
  <div class="col-md-4 mb-2">
    <input type="text" id="searchInput" class="form-control" placeholder="Поиск по парковке...">
  </div>
  <div class="col-md-4 mb-2">
    <select id="fineFilter" class="form-select">
      <option value="">Все бронирования</option>
      <option value="fine">Только со штрафом</option>
      <option value="no-fine">Только без штрафа</option>
    </select>
  </div>
  <div class="col-md-4 mb-2">
    <input type="date" id="dateFilter" class="form-control" placeholder="Дата бронирования">
  </div>
</div>

    <div class="scroll-box">
      <ul class="list-group mb-0">
{% for booking in finished_bookings %}
  <li class="list-group-item"
    data-parking="{{ booking.parkingzone.name|lower }}"
    data-hasfine="{% if booking.total_fine_amount > 0 %}yes{% else %}no{% endif %}"
    data-date="{{ booking.start_datetime|date:"Y-m-d" }}">
    <strong>{{ booking.parkingzone.name }}</strong><br>
    {{ booking.start_datetime|date:"d.m.Y H:i" }} – {{ booking.end_datetime|date:"d.m.Y H:i" }}<br>
    Статус: {{ booking.get_status_display }}<br>

    <strong>Цена брони:</strong> {{ booking.price|floatformat:0 }} руб.<br>
    {% with fine_total=booking.total_fine_amount %}
      {% if fine_total > 0 %}
        <span style="color:red;"><strong>Штраф:</strong> {{ fine_total|floatformat:0 }} руб.</span><br>
      {% else %}
        <span style="color:green;">Штраф: нет</span><br>
      {% endif %}
      <strong>Итого:</strong> {{ booking.total_cost|floatformat:0 }} руб.
    {% endwith %}
  </li>
{% endfor %}
      </ul>
    <p id="no-results" class="text-center mt-3" style="display:none; color: white;">Ничего не найдено.</p>

    </div>
  {% else %}
    <p>История отсутствует.</p>
  {% endif %}
</section>

<section id="section-fines" style="display: none;">
  <h4>Начисленные штрафы</h4>

  {% if fines %}
    <p><strong>Общая сумма штрафов:</strong> {{ total_fines|floatformat:2 }} руб.</p>

    <div class="scroll-box">
      <ul class="list-group mb-0">
        {% for fine in fines %}
          <li class="list-group-item">
            <strong>{{ fine.booking.parkingzone.name }}</strong><br>
            Дата: {{ fine.issued_at|date:"d.m.Y H:i" }}<br>
            Сумма: {{ fine.amount|floatformat:2 }} руб.<br>
            Причина: {{ fine.reason }}<br>
            {% if fine.is_paid %}
              <span style="color:green">Оплачен</span>
            {% else %}
              <span style="color:red">Не оплачен</span>
            {% endif %}
          </li>
        {% endfor %}
      </ul>
    </div>
  {% else %}
    <p>Штрафов пока нет.</p>
  {% endif %}
</section>

<section id="section-settings" style="display: none;">
<div class="glass personal-info-box mb-4">
  <h3 class="mb-3">Личные данные</h3>
  <p><strong>Email:</strong> {{ user.email }}</p>
  <p><strong>Госномер:</strong> {{ user.car_number }}</p>
  <p><strong>Дата регистрации:</strong> {{ user.date_joined|date:"d.m.Y H:i" }}</p>
  <p><strong>Последний вход:</strong> {{ user.last_login|date:"d.m.Y H:i" }}</p>
</div>
    {% if not user.car_number %}
  <div class="alert alert-warning">
    Чтобы бронировать парковочные места, пожалуйста, укажите номер автомобиля ниже.
  </div>
{% endif %}
  <form method="post" action="{% url 'booking:update_car_number' %}" class="mb-3">
    {% csrf_token %}
    <div class="input-group">
      <input type="text" name="new_car_number" placeholder="Новый госномер" class="form-control" required>
      <div class="input-group-append">
        <button type="submit" class="btn btn-outline-success">Сменить госномер</button>
      </div>
    </div>
  </form>

  <a href="{% url 'booking:password_reset' %}" class="btn btn-outline-primary btn-sm mb-2 w-100">Сбросить пароль</a>
  <a href="{% url 'booking:logout' %}" class="btn btn-outline-danger btn-sm w-100">Выйти из аккаунта</a>
</section>
    
<section id="section-verified" style="display: none;">
  <h4>Подтверждение аккаунта</h4>

  {% if not user.is_verified %}
    <p>Ваш аккаунт ещё не подтверждён.</p>
    <form method="post" action="{% url 'booking:verify_account' %}">
      {% csrf_token %}
        <div class="mb-3">
            <label for="id_account_type">Тип аккаунта</label>
            <select name="account_type" id="id_account_type" class="form-select" required>
              <option value="">Выберите тип</option>
              <option value="individual">Частное лицо</option>
              <option value="company">Компания</option>
            </select>
          </div>
        
          <div class="mb-3">
            <label for="id_phone_number">Номер телефона</label>
            <input type="text" name="phone_number" id="id_phone_number" class="form-control" placeholder="Введите номер телефона" required>
          </div>
        
          <div id="passport-block" class="mb-3" style="display:none;">
            <label for="id_passport_data">Паспортные данные</label>
            <input type="text" name="passport_data" id="id_passport_data" class="form-control" placeholder="Введите серию и номер паспорта">
          </div>
        
          <div id="company-block" style="display:none;">
            <div class="mb-3">
              <label for="id_company_name">Название компании</label>
              <input type="text" name="company_name" id="id_company_name" class="form-control" placeholder="Название компании">
            </div>
            <div class="mb-3">
              <label for="id_inn">ИНН компании</label>
              <input type="text" name="inn" id="id_inn" class="form-control" placeholder="ИНН компании">
            </div>
          </div>


      <button type="submit" class="btn btn-success w-100">Отправить заявку</button>
    </form>
  {% else %}
    <p style="color:#5bef5b;"><strong>Ваш аккаунт подтверждён.</strong></p>
    <a href="{% url 'booking:add_parking_zone' %}" class="btn btn-primary w-100 mb-2">Добавить парковку</a>
    <a href="{% url 'booking:my_parking_zones' %}" class="btn btn-outline-info w-100">Мои парковки</a>
  {% endif %}
</section>

<script>
  function showSection(id) {
    const sections = ['current', 'history', 'fines', 'verified', 'settings'];
    sections.forEach(name => {
      document.getElementById('section-' + name).style.display = (name === id) ? 'block' : 'none';
    });
  }
</script>
   

<script>
document.addEventListener("DOMContentLoaded", function () {
  const searchInput = document.getElementById("searchInput");
  const fineFilter = document.getElementById("fineFilter");
  const dateFilter = document.getElementById("dateFilter");
  const items = document.querySelectorAll("#section-history .list-group-item");
  const noResults = document.getElementById("no-results");

  function filterItems() {
    const search = searchInput.value.toLowerCase().trim();
    const fine = fineFilter.value;
    const selectedDate = dateFilter.value;

    let visibleCount = 0;

    items.forEach(item => {
      const parking = item.dataset.parking || "";
      const hasFine = item.dataset.hasfine || "";
      const bookingDate = item.dataset.date || "";

      let show = true;

      if (search && !parking.includes(search)) show = false;
      if (fine === "fine" && hasFine !== "yes") show = false;
      if (fine === "no-fine" && hasFine !== "no") show = false;
      if (selectedDate && bookingDate !== selectedDate) show = false;

      item.style.display = show ? "block" : "none";
      if (show) visibleCount++;
    });

    noResults.style.display = visibleCount === 0 ? "block" : "none";
  }

  searchInput.addEventListener("input", filterItems);
  fineFilter.addEventListener("change", filterItems);
  dateFilter.addEventListener("change", filterItems);
});
</script>
    <script>
document.addEventListener('DOMContentLoaded', function() {
  const accountTypeSelect = document.getElementById('id_account_type');
  const passportBlock = document.getElementById('passport-block');
  const companyBlock = document.getElementById('company-block');

  function toggleFields() {
    if (accountTypeSelect.value === 'individual') {
      passportBlock.style.display = 'block';
      companyBlock.style.display = 'none';
    } else if (accountTypeSelect.value === 'company') {
      passportBlock.style.display = 'none';
      companyBlock.style.display = 'block';
    } else {
      passportBlock.style.display = 'none';
      companyBlock.style.display = 'none';
    }
  }

  accountTypeSelect.addEventListener('change', toggleFields);
  toggleFields(); 
});
</script>

<script>
document.addEventListener('DOMContentLoaded', function() {
  const form = document.querySelector('form[action="{% url 'booking:verify_account' %}"]');
  const accountTypeSelect = document.getElementById('id_account_type');
  const passportDataInput = document.getElementById('id_passport_data');
  const companyNameInput = document.getElementById('id_company_name');
  const innInput = document.getElementById('id_inn');

  form.addEventListener('submit', function(event) {
    let valid = true;
    const accountType = accountTypeSelect.value;

    if (accountType === 'individual') {
  if (!passportDataInput.value.trim()) {
    valid = false;
    Swal.fire({
      icon: 'warning',
      title: 'Ошибка!',
      text: 'Пожалуйста, укажите паспортные данные.'
    });
  }
} else if (accountType === 'company') {
  if (!companyNameInput.value.trim()) {
    valid = false;
    Swal.fire({
      icon: 'warning',
      title: 'Ошибка!',
      text: 'Пожалуйста, укажите название компании.'
    });
  } else if (!innInput.value.trim()) {
    valid = false;
    Swal.fire({
      icon: 'warning',
      title: 'Ошибка!',
      text: 'Пожалуйста, укажите ИНН компании.'
    });
  }
}


    if (!valid) {
      event.preventDefault();
    }
  });
});
</script>
    
{% endblock %}
{% block mapscripts %}
{{ block.super }}
<script>
  ymaps.ready(function () {
    {% for booking in active_bookings %}
      ymaps.geocode("{{ booking.parkingzone.address }}").then(function (res) {
        const first = res.geoObjects.get(0);
        if (!first) return;

        const coords = first.geometry.getCoordinates();
        const map = new ymaps.Map("map-{{ booking.id }}", {
          center: coords,
          zoom: 16,
          controls: ['zoomControl']
        });

        const placemark = new ymaps.Placemark(coords, {
          balloonContent: "{{ booking.parkingzone.name }}"
        });

        map.geoObjects.add(placemark);
      });
    {% endfor %}
  });
</script>
{% endblock %}